---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: psql-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"  # Применяется ПЕРВЫМ
spec:
  project: default
  source:
    repoURL: https://github.com/IagodaSergei/argotests.git
    targetRevision: HEAD
    path: argocd-apps/psql-secrets/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: psql-18
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
