type: postgresql

mode: standalone

version:
  # -- PostgreSQL major version to use
  postgresql: "18"

cluster:
  # -- Number of instances
  instances: 2

  imageName: "ghcr.io/cloudnative-pg/postgresql:18.6-standard-trixie"

  annotations:
    container.apparmor.security.beta.kubernetes.io/postgres: unconfined
    container.apparmor.security.beta.kubernetes.io/initdb: unconfined

  storage:
    size: 8Gi
    storageClass: ""

  walStorage:
    enabled: true
    size: 1Gi
    storageClass: ""

  logLevel: "info"

  monitoring:
    # -- Whether to enable monitoring
    enabled: false

  initdb:
    database: test
    owner: test
    encoding: UTF8

  postgresql:
    # -- PostgreSQL configuration options (postgresql.conf)
    parameters:
      max_connections: "300"

    pg_hba: []

  roles: []
    # - name: cron_user
    #   ensure: present
    #   login: true
    #   passwordSecret:
    #     name: cron-user-password
    #   connectionLimit: -1
    #   inherit: true
    # - name: assetor_user
    #   ensure: present
    #   login: true
    #   passwordSecret:
    #     name: assetor-user-password
    #   connectionLimit: -1
    #   inherit: true
    # - name: lccore_user
    #   ensure: present
    #   login: true
    #   passwordSecret:
    #     name: lccore-user-password
    #   connectionLimit: -1
    #   inherit: true
    # - name: dviewer_user
    #   ensure: present
    #   login: true
    #   passwordSecret:
    #     name: dviewer-user-password
    #   connectionLimit: -1
    #   inherit: true
    # - name: audit_user
    #   ensure: present
    #   login: true
    #   passwordSecret:
    #     name: audit-user-password
    #   connectionLimit: -1
    #   inherit: true
    # - name: user_user
    #   ensure: present
    #   login: true
    #   passwordSecret:
    #     name: user-user-password
    #   connectionLimit: -1
    #   inherit: true
    # - name: mail_gateway_user
    #   ensure: present
    #   login: true
    #   passwordSecret:
    #     name: mail-gateway-user-password
    #   connectionLimit: -1
    #   inherit: true
    
backups:
  # -- You need to configure backups manually, so backups are disabled by default.
  enabled: false

databases: []
  # - name: audit
  #   ensure: present
  #   owner: audit_user
  #   encoding: UTF8

  # - name: userdb
  #   ensure: present
  #   owner: user_user
  #   encoding: UTF8

  # - name: mailer
  #   ensure: present
  #   owner: mail_gateway_user
  #   encoding: UTF8

  # - name: postgres
  #   ensure: present
  #   owner: postgres
  #   schemas:
  #     - name: pool
  #       owner: postgres
  #       ensure: present
  #     - name: activation
  #       owner: postgres
  #       ensure: present
  #     - name: catalog
  #       owner: postgres
  #       ensure: present
  #     - name: dviewer
  #       owner: postgres
  #       ensure: present
  #     - name: auth
  #       owner: postgres
  #       ensure: present

poolers:
  - name: rw
    type: rw
    poolMode: transaction
    instances: 2
    parameters:
      max_client_conn: "2000"
      default_pool_size: "50"
      min_pool_size: "10"
      reserve_pool_size: "20"
      reserve_pool_timeout: "5"

      server_idle_timeout: "60"
      client_idle_timeout: "300"
      idle_transaction_timeout: "60"

      log_connections: "1"
      log_disconnections: "1"
      log_pooler_errors: "1"
    template:
      spec:
        containers:
          - name: pgbouncer
            image: ghcr.io/cloudnative-pg/pgbouncer:1.25.1
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
  - name: ro
    type: ro
    poolMode: transaction
    instances: 2
    parameters:
      max_client_conn: "2000"
      default_pool_size: "50"
      min_pool_size: "10"
      reserve_pool_size: "20"
      reserve_pool_timeout: "5"

      server_idle_timeout: "60"
      client_idle_timeout: "300"
      idle_transaction_timeout: "60"

      log_connections: "1"
      log_disconnections: "1"
      log_pooler_errors: "1"
    template:
      spec:
        containers:
          - name: pgbouncer
            image: ghcr.io/cloudnative-pg/pgbouncer:1.25.1
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
