apiVersion: v1
kind: Secret
metadata:
  name: cron-user-password
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: cron_user
  password: "cron_pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: assetor-user-password
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: assetor_user
  password: "assetor_pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: lccore-user-password
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: lccore_user
  password: "lccore_pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: dviewer-user-password
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: dviewer_user
  password: "dviewer_pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: audit-user-password
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: audit_user
  password: "audit_pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-user-password
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: user_user
  password: "user_pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: mail-gateway-user-password
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: mail_gateway_user
  password: "mail_gateway_pass"
